apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 3
  template:
    metadata:
      labels:
        app: my-app
    spec:
      terminationGracePeriodSeconds: 1
      containers:
       - name: nginx
         image: vinsdocker/nginx-gke
         ports:
         - containerPort: 80
---       
apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  terminationGracePeriodSeconds: 1 #when deleting the  pod, the kubernetes send SIGTERM (telling politely to exit) to the container. Once the probided time is over, kube sends SIGKILL (terminates immediately)
  containers:
    - name: demo
      image: vinsdocker/util
      args:
      - "sleep"
      - "3600"

#Container starts → runs sleep 3600.
#You delete the Pod.
#Kubernetes sends SIGTERM → the sleep process exits immediately (because sleep obeys SIGTERM).
#If it didn’t, then after your grace period Kubernetes would use SIGKILL.
