apiVersion: v1
kind: Pod
metadata:
  name: my-pod-port-forwarding
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - name: "web-port"
      containerPort: 80   
      protocol: TCP #default protocol