apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  selector:
    app: nginx   # must match the labels of your nginx deployment
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
#cmd to create service using yaml file 
#kubectl create -f nginx-nodeport.yaml

#cmd to see the list of services
#kubectl get svc