apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 3
  template:
    metadata:
      labels:
        app: my-app
    spec:
      terminationGracePeriodSeconds: 1
      containers:
       - name: nginx
         image: vinsdocker/nginx-gke
         ports:
         - containerPort: 80
---       
apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - port: 80 #service port
      targetPort: 80 #pod port
      nodePort: 30001 #node's port - explicitily say the port if you want a specific port
      #receives traffic from outside
