apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deploy
spec:
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      apps: order-service
  replicas: 3
  template:
    metadata:
      labels:
        apps: order-service
    spec:
      containers:
      - name: order-service
        image: vinsdocker/k8s-app:v2
        ports:
        - name: "app-port"
          containerPort: 80
---       
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  terminationGracePeriodSeconds: 1 #when deleting the  pod, the kubernetes send SIGTERM (telling politely to exit) to the container. Once the probided time is over, kube sends SIGKILL (terminates immediately)
  containers:
    - name: demo
      image: vinsdocker/util
      args:
      - "sleep"
      - "3600"