# vinsdocker/k8s-probe-demo uses nginx
# nginx will start after 10 seconds
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-app
spec:
  terminationGracePeriodSeconds: 1
  containers:
  - name: probe-demo
    image: vinsdocker/k8s-probe-demo
    startupProbe:
      httpGet:
        path: /
        port: 80
      periodSeconds: 1
      failureThreshold: 30
    livenessProbe:
      httpGet:
        path: /live.html
        port: 80
      periodSeconds: 1
      failureThreshold: 3    
    readinessProbe:
      httpGet:
        path: /ready.html
        port: 80
      periodSeconds: 1
      failureThreshold: 1       
---
apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  selector:
    app: my-app
  ports:
  - port: 80
    targetPort: 80      

    
    
# 1. Pod creation
# A Pod called my-pod is created running the image vinsdocker/k8s-probe-demo.
# The Pod is labeled app: my-app so it can be matched by the Service.

# 2. Startup Probe
# Kubernetes checks http://<pod-ip>:80/ every 1 second.
# The container gets 30 seconds total (1 × 30) to start up.
# Since vinsdocker/k8s-probe-demo starts NGINX after ~10 seconds, it’ll pass before timeout.
# Until this probe succeeds, the other probes are disabled — preventing premature restarts.
# Once it succeeds, Kubernetes considers the container started.

# 3. Liveness Probe
# Runs after the startup probe succeeds.
# Checks http://<pod-ip>:80/live.html every 1 second.
# If it fails 3 consecutive times → Kubernetes restarts the container.
# Ensures the container doesn’t get stuck or hang.

# 4. Readiness Probe
# Checks if the app is ready to serve traffic.
# If /ready.html fails, the container stays running but is marked “NotReady.”
# Kubernetes removes the Pod from the Service endpoints (so it stops receiving requests).
# This keeps traffic away from unhealthy pods without killing them.

# 5. Service
# The Service forwards traffic to any Pod with app: my-app label.
# Because of the readiness probe, the Service will only send traffic to Pods that are marked as Ready.
# So:
# While startup is still running → not ready → no traffic.
# Once ready.html responds OK → added to Service → receives traffic.
# If readiness fails later → traffic is removed automatically.